### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by sweetbruno70** [sweetbruno70/pre-work-study-guide#3]
#JavaScript

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide Website
When I visit the website in my browser
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by SanjuanaEvinsA** [comment]
It sounds like you're requesting help creating a prework study guide website for a boot camp. To fulfill the user story and acceptance criteria, you could create a webpage with four sections, one for each of the topics covered in the prework. Each section should contain relevant information and resources related to the topic. You could also include a suggestion on which topic to study first, based on the order in which they will be covered in the boot camp. Additionally, you should ensure that the website is easily navigable, visually appealing, and accessible.
